export const SUBMIT_REGISTERINTODORM = 'SUBMIT_REGISTERINTODORM'
export const SET_RELATIVE = 'SET_RELATIVE'
export const SET_RELATIVE_REGISTER_STEP = 'SET_RELATIVE_REGISTER_STEP'
export const SUBMIT_REGISTER_RELATIVE = 'SUBMIT_REGISTER_RELATIVE'
export const SET_TO_FIRST_STEP = 'SET_TO_FIRST_STEP'
export const SET_SELECTED_STUDENT = 'SET_SELECTED_STUDENT'


