export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
export const UPDATE_IS_READ = 'UPDATE_IS_READ';
export const UPDATE_IS_READ_ALL = 'UPDATE_IS_READ_ALL';